version: '3.7'

services:
  node:
    container_name: node_server
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - .:/app
    command: yarn dev
    networks:
      - common
    environment:
      PORT: 5173
      MONGO_URL: 'mongodb://mongo/example'
      NODE_ENV: 'development'

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - common
  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx/conf.d/:/etc/nginx/conf.d
  #   networks:
  #     - common

networks:
  common:
